
-- Hapus kebijakan RLS yang lama jika ada
DROP POLICY IF EXISTS "Admin can manage all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;

DROP POLICY IF EXISTS "Admin can manage all leave requests" ON public.leave_requests;
DROP POLICY IF EXISTS "Users can manage their own leave requests" ON public.leave_requests;

DROP POLICY IF EXISTS "Admin can manage all leave balances" ON public.leave_balances;
DROP POLICY IF EXISTS "Users can view their own leave balances" ON public.leave_balances;

-- Hapus tabel yang sudah ada secara berurutan untuk menghindari error foreign key
DROP TABLE IF EXISTS public.leave_requests;
DROP TABLE IF EXISTS public.leave_balances;
DROP TABLE IF EXISTS public.profiles;

-- Pastikan tabel leave_types dihapus jika ada
DROP TABLE IF EXISTS public.leave_types;


-- 1. Tabel PROFILES
-- Menyimpan data publik untuk setiap pengguna
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY,
  updated_at timestamp with time zone,
  name text,
  email text,
  nip text,
  pangkat text,
  golongan text,
  jabatan text,
  satuanKerja text, -- 'satuanKerja' instead of 'satuan_kerja'
  avatar_url text,
  role text DEFAULT 'anggota',
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Komentar untuk kejelasan
COMMENT ON TABLE public.profiles IS 'Menyimpan data profil publik untuk setiap pengguna.';
COMMENT ON COLUMN public.profiles.role IS 'Peran pengguna, bisa ''admin'' atau ''anggota''.';


-- 2. Tabel LEAVE_BALANCES
-- Menyimpan jatah cuti tahunan untuk setiap anggota
CREATE TABLE public.leave_balances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  year integer NOT NULL,
  total_days integer NOT NULL DEFAULT 12,
  used_days integer NOT NULL DEFAULT 0,
  CONSTRAINT leave_balances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE,
  CONSTRAINT leave_balances_unique_user_year UNIQUE (user_id, year)
);

-- Komentar untuk kejelasan
COMMENT ON TABLE public.leave_balances IS 'Menyimpan saldo cuti tahunan untuk setiap anggota.';


-- 3. Tabel LEAVE_REQUESTS
-- Menyimpan semua pengajuan cuti
CREATE TABLE public.leave_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  duration integer NOT NULL,
  title text NOT NULL,
  reason text,
  status text NOT NULL DEFAULT 'Menunggu', -- 'Menunggu', 'Disetujui', 'Ditolak'
  attachment_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT leave_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Komentar untuk kejelasan
COMMENT ON TABLE public.leave_requests IS 'Menyimpan semua pengajuan cuti dari anggota.';
COMMENT ON COLUMN public.leave_requests.status IS 'Status pengajuan: Menunggu, Disetujui, Ditolak.';


-- Mengaktifkan Row Level Security (RLS) untuk semua tabel
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;


-- 4. Kebijakan RLS (Row Level Security)

-- Kebijakan untuk tabel PROFILES
CREATE POLICY "Admin can manage all profiles" ON public.profiles FOR ALL
  USING (public.get_user_role() = 'admin');

CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- Kebijakan untuk tabel LEAVE_REQUESTS
CREATE POLICY "Admin can manage all leave requests" ON public.leave_requests FOR ALL
  USING (public.get_user_role() = 'admin');

CREATE POLICY "Users can manage their own leave requests" ON public.leave_requests FOR ALL
  USING (auth.uid() = user_id);

-- Kebijakan untuk tabel LEAVE_BALANCES
CREATE POLICY "Admin can manage all leave balances" ON public.leave_balances FOR ALL
  USING (public.get_user_role() = 'admin');

CREATE POLICY "Users can view their own leave balances" ON public.leave_balances FOR SELECT
  USING (auth.uid() = user_id);


-- 5. Fungsi Helper
-- Fungsi untuk mendapatkan peran pengguna saat ini
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
begin
  if auth.uid() is null then
    return 'anon';
  else
    return (
      select role
      from public.profiles
      where id = auth.uid()
    );
  end if;
end;
$$;


-- 6. Trigger dan Fungsi Trigger
-- Fungsi yang akan dipanggil oleh trigger saat ada pengguna baru
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
declare
  current_year integer;
begin
  -- Masukkan baris baru ke public.profiles
  insert into public.profiles (id, email, name, role)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    'anggota'
  );

  -- Buat saldo cuti awal untuk tahun berjalan
  current_year := extract(year from now());
  insert into public.leave_balances (user_id, year, total_days)
  values (new.id, current_year, 12);
  
  return new;
end;
$$;

-- Hapus trigger lama jika ada
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Buat trigger yang akan memanggil fungsi handle_new_user
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();


-- Fungsi untuk memperbarui saldo cuti secara atomik
CREATE OR REPLACE FUNCTION public.update_leave_balance(p_user_id uuid, p_year integer, p_days_to_add integer)
RETURNS void
LANGUAGE plpgsql
AS $$
begin
  -- Coba update saldo jika sudah ada
  UPDATE public.leave_balances
  SET used_days = used_days + p_days_to_add
  WHERE user_id = p_user_id AND year = p_year;

  -- Jika tidak ada baris yang diupdate (misal, saldo untuk tahun tsb belum dibuat), buat baru
  IF NOT FOUND THEN
    INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
    VALUES (p_user_id, p_year, 12, p_days_to_add);
  END IF;
end;
$$;
