-- supabase.sql
-- File ini mendefinisikan skema database lengkap, RLS, dan fungsi.
-- Jalankan konten file ini di SQL Editor Supabase Anda untuk setup awal.

-- 1. Buat Tabel Profil Pengguna
-- Tabel ini menyimpan data publik yang terhubung dengan tabel `auth.users`.
CREATE TABLE
  public.profiles (
    id uuid NOT NULL,
    updated_at timestamp with time zone NULL,
    name character varying NULL,
    id_pjlp text NULL,
    avatar_url text NULL,
    role text NULL DEFAULT 'anggota'::text,
    phone text NULL,
    email character varying NULL,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_id_pjlp_key UNIQUE (id_pjlp),
    CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
  );

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. Buat Tabel Permintaan Cuti
-- Menyimpan semua riwayat dan permintaan cuti yang diajukan oleh pengguna.
CREATE TABLE
  public.leave_requests (
    id bigint generated by default as identity,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    title text NOT NULL,
    reason text NULL,
    status text NOT NULL DEFAULT 'Menunggu'::text,
    duration integer NOT NULL,
    attachment_url text NULL,
    is_read boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
    CONSTRAINT leave_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE
  );

ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;


-- 3. Buat Tabel Saldo Cuti
-- Menyimpan jatah cuti tahunan untuk setiap pengguna.
CREATE TABLE
  public.leave_balances (
    id bigint generated by default as identity,
    user_id uuid NOT NULL,
    year integer NOT NULL,
    total_days integer NOT NULL DEFAULT 12,
    used_days integer NOT NULL DEFAULT 0,
    CONSTRAINT leave_balances_pkey PRIMARY KEY (id),
    CONSTRAINT leave_balances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON DELETE CASCADE,
    CONSTRAINT leave_balances_user_id_year_key UNIQUE (user_id, year)
  );

ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;

-- 4. Setel Kebijakan Row Level Security (RLS)

-- PROFILES
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admin can do anything." ON public.profiles FOR ALL USING (public.get_user_role() = 'admin');

-- LEAVE_REQUESTS
CREATE POLICY "Users can view their own leave requests." ON public.leave_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create leave requests." ON public.leave_requests FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can't update or delete requests." ON public.leave_requests FOR UPDATE USING (false);
CREATE POLICY "Admin can see all requests." ON public.leave_requests FOR SELECT USING (public.get_user_role() = 'admin');
CREATE POLICY "Admin can update any request." ON public.leave_requests FOR UPDATE USING (public.get_user_role() = 'admin');

-- LEAVE_BALANCES
CREATE POLICY "Users can view their own leave balances." ON public.leave_balances FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admin can view all leave balances." ON public.leave_balances FOR SELECT USING (public.get_user_role() = 'admin');
CREATE POLICY "Admin can update/insert leave balances." ON public.leave_balances FOR ALL USING (public.get_user_role() = 'admin');


-- 5. Buat Fungsi dan Trigger

-- Fungsi untuk mendapatkan peran pengguna saat ini
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  user_role text;
BEGIN
  SELECT role INTO user_role FROM public.profiles WHERE id = auth.uid();
  RETURN user_role;
END;
$$;


-- Fungsi untuk menyinkronkan data pengguna baru ke tabel profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, id_pjlp, phone, role)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'name',
    NEW.email,
    NEW.raw_user_meta_data->>'id_pjlp',
    NEW.raw_user_meta_data->>'phone',
    'anggota' -- Default role
  );
  
  -- Juga, buat entri saldo cuti awal untuk tahun berjalan
  INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
  VALUES (NEW.id, EXTRACT(YEAR FROM now())::integer, 12, 0);

  RETURN NEW;
END;
$$;

-- Trigger yang memanggil handle_new_user setiap kali user baru dibuat
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();


-- Fungsi untuk memperbarui saldo cuti secara atomik
CREATE OR REPLACE FUNCTION public.update_leave_balance(p_user_id uuid, p_year integer, p_days_to_add integer)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.leave_balances
  SET used_days = used_days + p_days_to_add
  WHERE user_id = p_user_id AND year = p_year;
END;
$$;
