-- ### SKEMA DATABASE SIAP CUTI (v1.2 - Optimized) ###
-- Urutan eksekusi:
-- 1.  Pembuatan Tabel (Struktur Data)
-- 2.  Pembuatan Indeks (Optimasi Performa)
-- 3.  Pembuatan Fungsi (Logika & Helper)
-- 4.  Pengaktifan RLS & Penerapan Kebijakan Keamanan
-- 5.  Pembuatan Pemicu (Otomatisasi)

-- =============================================
-- 1. PEMBUATAN TABEL
-- =============================================

-- Tabel untuk menyimpan profil pengguna, terhubung ke tabel auth.users bawaan Supabase.
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name text,
    id_pjlp text UNIQUE,
    phone text,
    email text UNIQUE,
    role text DEFAULT 'anggota',
    avatar_url text,
    updated_at timestamp with time zone
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.profiles IS 'Stores public profile information for each user.';

-- Tabel untuk menyimpan histori pengajuan cuti.
CREATE TABLE public.leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title text NOT NULL,
    reason text,
    start_date date NOT NULL,
    end_date date NOT NULL,
    duration integer NOT NULL,
    status text NOT NULL DEFAULT 'Menunggu',
    attachment_url text,
    is_read_by_user boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.leave_requests IS 'Stores leave requests submitted by users.';

-- Tabel untuk menyimpan rekapitulasi saldo cuti tahunan setiap pengguna.
CREATE TABLE public.leave_balances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    year integer NOT NULL,
    total_days integer NOT NULL DEFAULT 12,
    used_days integer NOT NULL DEFAULT 0,
    UNIQUE (user_id, year)
);
ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.leave_balances IS 'Stores annual leave balance for each user.';

-- Tabel untuk notifikasi admin.
CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE, -- Admin user_id
    leave_request_id bigint NOT NULL REFERENCES public.leave_requests(id) ON DELETE CASCADE,
    message text NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE public.notifications IS 'Notifications for admins about new leave requests.';


-- =============================================
-- 2. PEMBUATAN INDEKS (OPTIMASI PERFORMA)
-- =============================================
-- Membuat pencarian data lebih cepat.

CREATE INDEX idx_profiles_role ON public.profiles(role);
CREATE INDEX idx_profiles_id_pjlp ON public.profiles(id_pjlp);
CREATE INDEX idx_leave_requests_user_id ON public.leave_requests(user_id);
CREATE INDEX idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX idx_leave_balances_user_id_year ON public.leave_balances(user_id, year);
CREATE INDEX idx_notifications_user_id ON public.notifications(user_id);


-- =============================================
-- 3. PEMBUATAN FUNGSI
-- =============================================

-- Fungsi untuk mendapatkan peran (role) dari pengguna yang sedang login.
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Fungsi untuk membuat profil dan saldo cuti awal saat pengguna baru mendaftar.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  current_year integer := date_part('year', now());
BEGIN
  -- Membuat profil baru
  INSERT INTO public.profiles (id, name, id_pjlp, phone, email, role)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'name',
    new.raw_user_meta_data->>'id_pjlp',
    new.raw_user_meta_data->>'phone',
    new.email,
    'anggota' -- Default role
  );

  -- Membuat saldo cuti awal untuk tahun berjalan
  INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
  VALUES (new.id, current_year, 12, 0);

  RETURN new;
END;
$$;

-- Fungsi untuk membuat notifikasi ke semua admin saat ada pengajuan cuti baru.
CREATE OR REPLACE FUNCTION public.create_admin_notification_for_new_leave()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  admin_record record;
  notification_message text;
BEGIN
  -- Pesan notifikasi
  notification_message := (SELECT name FROM public.profiles WHERE id = NEW.user_id) || ' telah mengajukan cuti baru.';

  -- Loop melalui semua admin dan buat notifikasi untuk mereka
  FOR admin_record IN SELECT id FROM public.profiles WHERE role = 'admin' LOOP
    INSERT INTO public.notifications (user_id, leave_request_id, message)
    VALUES (admin_record.id, NEW.id, notification_message);
  END LOOP;

  RETURN NEW;
END;
$$;

-- Fungsi untuk mereset saldo cuti semua anggota di awal tahun.
CREATE OR REPLACE FUNCTION public.handle_new_year_leave_balances()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    user_record RECORD;
    current_year INTEGER := EXTRACT(YEAR FROM NOW());
BEGIN
    FOR user_record IN SELECT id FROM public.profiles WHERE role = 'anggota' LOOP
        -- Hanya insert jika data untuk tahun baru belum ada, untuk menghindari duplikasi
        INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
        VALUES (user_record.id, current_year, 12, 0)
        ON CONFLICT (user_id, year) DO NOTHING;
    END LOOP;
END;
$$;

-- FIX: Memberikan izin kepada 'postgres' untuk memodifikasi sesi, diperlukan oleh fungsi login kustom.
GRANT update ON TABLE auth.sessions TO postgres;

-- Fungsi RPC untuk login menggunakan ID PJLP, menggabungkan beberapa query menjadi satu.
CREATE OR REPLACE FUNCTION public.login_with_id_pjlp(p_id_pjlp text, p_password text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_email text;
    v_user_id uuid;
    v_role text;
    v_login_result json;
BEGIN
    -- 1. Cari email dan role berdasarkan ID PJLP
    SELECT email, id, role INTO v_email, v_user_id, v_role
    FROM public.profiles
    WHERE id_pjlp = p_id_pjlp;

    -- 2. Jika ID PJLP tidak ditemukan
    IF v_email IS NULL THEN
        RETURN json_build_object('error', 'ID PJLP tidak ditemukan.');
    END IF;

    -- 3. Coba untuk login menggunakan fungsi bawaan Supabase
    -- Ini akan memverifikasi password dan membuat sesi jika berhasil.
    SELECT sign_in INTO v_login_result FROM auth.sign_in(v_email, p_password);

    -- 4. Cek hasil login
    IF v_login_result->>'error' IS NOT NULL THEN
        -- Jika ada error dari auth.sign_in (misal: password salah)
        RETURN json_build_object('error', 'Password yang Anda masukkan salah.');
    END IF;
    
    -- 5. Jika login berhasil, kembalikan data yang dibutuhkan aplikasi
    RETURN json_build_object(
        'success', true,
        'user_id', v_user_id,
        'role', v_role,
        'email', v_email
    );
EXCEPTION
    -- Menangani kesalahan tak terduga
    WHEN others THEN
        RETURN json_build_object('error', 'Terjadi kesalahan internal yang tidak diketahui saat login.');
END;
$$;


-- =============================================
-- 4. KEBIJAKAN KEAMANAN (ROW LEVEL SECURITY)
-- =============================================

-- Kebijakan untuk tabel profiles
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles." ON public.profiles FOR SELECT TO authenticated USING (get_user_role() = 'admin');
CREATE POLICY "Admins can manage all profiles." ON public.profiles FOR ALL TO authenticated USING (get_user_role() = 'admin') WITH CHECK (get_user_role() = 'admin');

-- Kebijakan untuk tabel leave_requests
CREATE POLICY "Users can manage their own leave requests." ON public.leave_requests FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all leave requests." ON public.leave_requests FOR SELECT TO authenticated USING (get_user_role() = 'admin');
CREATE POLICY "Admins can update leave requests." ON public.leave_requests FOR UPDATE TO authenticated USING (get_user_role() = 'admin') WITH CHECK (get_user_role() = 'admin');

-- Kebijakan untuk tabel leave_balances
CREATE POLICY "Users can view their own leave balance." ON public.leave_balances FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all leave balances." ON public.leave_balances FOR SELECT TO authenticated USING (get_user_role() = 'admin');
CREATE POLICY "Admins can update all leave balances." ON public.leave_balances FOR UPDATE TO authenticated USING (get_user_role() = 'admin') WITH CHECK (get_user_role() = 'admin');

-- Kebijakan untuk tabel notifications
CREATE POLICY "Admins can manage their own notifications." ON public.notifications FOR ALL TO authenticated USING (auth.uid() = user_id AND get_user_role() = 'admin');


-- =============================================
-- 5. PEMICU (TRIGGERS)
-- =============================================

-- Pemicu untuk menjalankan `handle_new_user` setiap kali pengguna baru mendaftar di Supabase Auth.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Pemicu untuk menjalankan `create_admin_notification_for_new_leave` setiap kali ada pengajuan cuti baru.
CREATE TRIGGER on_leave_request_created
  AFTER INSERT ON public.leave_requests
  FOR EACH ROW EXECUTE PROCEDURE public.create_admin_notification_for_new_leave();

-- ### AKHIR DARI SKEMA ###
