-- -----------------------------------------------------------------------------------------------
-- 1. TABEL PENGGUNA & PROFIL
-- Tabel ini menyimpan data tambahan untuk pengguna, yang tidak ada di tabel `auth.users` bawaan Supabase.
-- -----------------------------------------------------------------------------------------------
CREATE TABLE
  public.profiles (
    id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    name TEXT,
    id_pjlp TEXT UNIQUE,
    phone TEXT,
    email TEXT,
    role TEXT DEFAULT 'anggota',
    avatar_url TEXT,
    updated_at TIMESTAMPTZ,
    PRIMARY KEY (id)
  );

-- Function untuk menyalin data dari `auth.users` ke `public.profiles` saat ada pengguna baru.
CREATE OR REPLACE FUNCTION public.handle_new_user () RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, id_pjlp, phone, email, role, avatar_url, updated_at)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'name',
    NEW.raw_user_meta_data ->> 'id_pjlp',
    NEW.raw_user_meta_data ->> 'phone',
    NEW.email,
    'anggota',
    NEW.raw_user_meta_data ->> 'avatar_url',
    NOW()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger yang akan menjalankan function `handle_new_user` setelah ada user baru di `auth.users`.
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_user ();

-- Function untuk mengambil role pengguna saat ini.
CREATE OR REPLACE FUNCTION public.get_user_role () RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT role FROM public.profiles WHERE id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------------------------
-- 2. TABEL PENGAJUAN CUTI (leave_requests)
-- Tabel ini menyimpan semua data pengajuan cuti dari para pengguna.
-- -----------------------------------------------------------------------------------------------
CREATE TABLE
  public.leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    title TEXT NOT NULL,
    reason TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration INT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Menunggu',
    attachment_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_read_by_user BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id)
  );

-- Function untuk memperbarui kolom `updated_at` secara otomatis.
CREATE OR REPLACE FUNCTION public.update_updated_at_column () RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger yang akan menjalankan function `update_updated_at_column`.
CREATE TRIGGER handle_leave_requests_update
BEFORE UPDATE ON public.leave_requests FOR EACH ROW
EXECUTE PROCEDURE public.update_updated_at_column ();

-- -----------------------------------------------------------------------------------------------
-- 3. TABEL SALDO CUTI (leave_balances)
-- Tabel ini menyimpan informasi jatah cuti tahunan setiap pengguna.
-- -----------------------------------------------------------------------------------------------
CREATE TABLE
  public.leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles ON DELETE CASCADE,
    year INT NOT NULL,
    total_days INT NOT NULL DEFAULT 12,
    used_days INT NOT NULL DEFAULT 0,
    UNIQUE (user_id, year),
    PRIMARY KEY (id)
  );

-- Function untuk membuat entri saldo cuti baru saat pengguna baru ditambahkan.
CREATE OR REPLACE FUNCTION public.create_initial_leave_balance() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
  VALUES (NEW.id, EXTRACT(YEAR FROM NOW())::integer, 12, 0);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger yang akan menjalankan function `create_initial_leave_balance` setelah profil baru dibuat.
CREATE TRIGGER on_profile_created
AFTER INSERT ON public.profiles FOR EACH ROW
EXECUTE PROCEDURE public.create_initial_leave_balance();

-- -----------------------------------------------------------------------------------------------
-- 4. TABEL NOTIFIKASI (notifications)
-- Tabel ini menyimpan notifikasi untuk admin saat ada pengajuan cuti baru.
-- -----------------------------------------------------------------------------------------------
CREATE TABLE
  public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL REFERENCES public.profiles ON DELETE CASCADE, -- ID admin yang akan menerima notifikasi
    leave_request_id BIGINT NOT NULL REFERENCES public.leave_requests ON DELETE CASCADE,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
  );

-- Function untuk membuat notifikasi kepada semua admin saat ada pengajuan cuti baru.
CREATE OR REPLACE FUNCTION public.create_admin_notification_for_new_leave() RETURNS TRIGGER AS $$
DECLARE
  admin_record RECORD;
  user_name TEXT;
BEGIN
  -- Ambil nama pemohon dari tabel profiles
  SELECT name INTO user_name FROM public.profiles WHERE id = NEW.user_id;

  -- Loop melalui semua user dengan role 'admin'
  FOR admin_record IN SELECT id FROM public.profiles WHERE role = 'admin' LOOP
    INSERT INTO public.notifications (user_id, leave_request_id, message, is_read)
    VALUES (admin_record.id, NEW.id, user_name || ' mengajukan cuti baru: ' || NEW.title, FALSE);
  END LOOP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger yang akan menjalankan function `create_admin_notification_for_new_leave` setelah ada pengajuan cuti baru.
CREATE TRIGGER on_new_leave_request
AFTER INSERT ON public.leave_requests FOR EACH ROW
EXECUTE PROCEDURE public.create_admin_notification_for_new_leave();


-- -----------------------------------------------------------------------------------------------
-- 5. FUNGSI-FUNGSI HELPER (RPC)
-- Kumpulan fungsi yang bisa dipanggil dari aplikasi untuk melakukan operasi kompleks.
-- -----------------------------------------------------------------------------------------------

-- Function untuk meng-handle reset saldo cuti di awal tahun.
CREATE OR REPLACE FUNCTION public.handle_new_year_leave_balances()
RETURNS void AS $$
DECLARE
  user_profile record;
  current_year integer;
BEGIN
  current_year := EXTRACT(YEAR FROM NOW());

  -- Loop melalui semua profil pengguna dengan role 'anggota'
  FOR user_profile IN SELECT id FROM public.profiles WHERE role = 'anggota' LOOP
    -- Cek apakah sudah ada entri saldo untuk tahun ini
    IF NOT EXISTS (
      SELECT 1
      FROM public.leave_balances
      WHERE user_id = user_profile.id AND year = current_year
    ) THEN
      -- Jika belum ada, buat entri baru dengan saldo 12 hari
      INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
      VALUES (user_profile.id, current_year, 12, 0);
    END IF;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Function untuk login menggunakan ID PJLP, bukan email.
CREATE OR REPLACE FUNCTION public.login_with_id_pjlp(p_id_pjlp TEXT, p_password TEXT)
RETURNS json AS $$
DECLARE
  user_email TEXT;
  user_id UUID;
  user_role TEXT;
  session_data JSON;
BEGIN
  -- 1. Cari email & id berdasarkan id_pjlp
  SELECT email, id, role INTO user_email, user_id, user_role
  FROM public.profiles
  WHERE id_pjlp = p_id_pjlp;

  -- 2. Jika tidak ditemukan, kembalikan error
  IF user_email IS NULL THEN
    RETURN json_build_object('error', 'ID PJLP tidak ditemukan.');
  END IF;
  
  -- 3. Coba login menggunakan email yang ditemukan.
  -- Ini memerlukan role `supabase_auth_admin` yang harus diberikan ke `postgres` user.
  -- GRANT supabase_auth_admin TO postgres;
  SELECT sign_in_with_password(user_email, p_password) INTO session_data;

  -- 4. Cek hasil dari `sign_in_with_password`
  IF session_data ->> 'access_token' IS NULL THEN
     RETURN json_build_object('error', 'Password yang Anda masukkan salah.');
  END IF;
  
  -- 5. Jika berhasil, kembalikan role pengguna.
  RETURN json_build_object('success', true, 'role', user_role);

EXCEPTION WHEN others THEN
    -- Menangkap exception lain, misalnya jika fungsi `sign_in` tidak ada atau error lain.
    RAISE WARNING 'Login RPC Error: %', SQLERRM;
    RETURN json_build_object('error', 'Terjadi kesalahan internal saat login.');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- -----------------------------------------------------------------------------------------------
-- 6. PENGATURAN HAK AKSES (ROW LEVEL SECURITY - RLS)
-- Ini adalah bagian paling penting untuk keamanan. RLS memastikan pengguna hanya bisa melihat
-- dan mengubah data yang menjadi haknya.
-- -----------------------------------------------------------------------------------------------

-- Aktifkan RLS untuk semua tabel
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Hapus policy yang mungkin sudah ada sebelumnya untuk kebersihan
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
DROP POLICY IF EXISTS "Admins can manage all profiles." ON public.profiles;

DROP POLICY IF EXISTS "Users can view their own leave requests." ON public.leave_requests;
DROP POLICY IF EXISTS "Users can create their own leave requests." ON public.leave_requests;
DROP POLICY IF EXISTS "Admins can view all leave requests." ON public.leave_requests;
DROP POLICY IF EXISTS "Admins can update status of leave requests." ON public.leave_requests;

DROP POLICY IF EXISTS "Users can view their own leave balances." ON public.leave_balances;
DROP POLICY IF EXISTS "Admins can view all leave balances." ON public.leave_balances;

DROP POLICY IF EXISTS "Users can view their own notifications." ON public.notifications;
DROP POLICY IF EXISTS "Users can update their own notifications." ON public.notifications;


-- Kebijakan untuk Tabel `profiles`
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid () = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid () = id);
CREATE POLICY "Admins can manage all profiles." ON public.profiles FOR ALL USING (public.get_user_role() = 'admin');

-- Kebijakan untuk Tabel `leave_requests`
CREATE POLICY "Users can view their own leave requests." ON public.leave_requests FOR SELECT USING (auth.uid () = user_id);
CREATE POLICY "Users can create their own leave requests." ON public.leave_requests FOR INSERT WITH CHECK (auth.uid () = user_id);
CREATE POLICY "Admins can view all leave requests." ON public.leave_requests FOR SELECT USING (public.get_user_role() = 'admin');
CREATE POLICY "Admins can update status of leave requests." ON public.leave_requests FOR UPDATE USING (public.get_user_role() = 'admin') WITH CHECK (public.get_user_role() = 'admin');

-- Kebijakan untuk Tabel `leave_balances`
CREATE POLICY "Users can view their own leave balances." ON public.leave_balances FOR SELECT USING (auth.uid () = user_id);
CREATE POLICY "Admins can view all leave balances." ON public.leave_balances FOR SELECT USING (public.get_user_role() = 'admin');

-- Kebijakan untuk Tabel `notifications`
CREATE POLICY "Users can view their own notifications." ON public.notifications FOR SELECT USING (auth.uid () = user_id);
CREATE POLICY "Users can update their own notifications." ON public.notifications FOR UPDATE USING (auth.uid () = user_id);

-- -----------------------------------------------------------------------------------------------
-- 7. PENGATURAN PENYIMPANAN (STORAGE)
-- Konfigurasi untuk bucket penyimpanan file lampiran.
-- -----------------------------------------------------------------------------------------------
INSERT INTO
  storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('lampiran-cuti', 'lampiran-cuti', TRUE, 5242880, '{"image/jpeg","image/png","application/pdf"}') ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Give users access to own folder" ON storage.objects FOR SELECT USING (bucket_id = 'lampiran-cuti' AND owner = auth.uid());
CREATE POLICY "Allow users to upload to their folder" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'lampiran-cuti' AND owner = auth.uid());

-- -----------------------------------------------------------------------------------------------
-- 8. OPTIMASI PERFORMA (INDEXING)
-- Menambahkan indeks pada kolom yang sering digunakan untuk filter atau join.
-- Ini akan membuat query menjadi jauh lebih cepat saat data sudah banyak.
-- -----------------------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles (role);
CREATE INDEX IF NOT EXISTS idx_leave_requests_user_id ON public.leave_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests (status);
CREATE INDEX IF NOT EXISTS idx_leave_balances_user_id_year ON public.leave_balances (user_id, year);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications (user_id);
