
-- ## SIAP CUTI - Supabase Schema ##
-- Skrip ini dirancang untuk dijalankan pada proyek Supabase yang baru atau kosong.
-- Urutan eksekusi sangat penting.

-- 1. Setup Tabel Utama
-- Tabel untuk menyimpan data profil pengguna, diperluas dari auth.users.
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  id_pjlp TEXT UNIQUE,
  email TEXT UNIQUE,
  phone TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'anggota',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
-- Tabel untuk menyimpan pengajuan cuti.
CREATE TABLE public.leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  reason TEXT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  duration INT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Menunggu', -- Menunggu, Disetujui, Ditolak
  attachment_url TEXT,
  is_read_by_user BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
-- Tabel untuk menyimpan rekap saldo cuti tahunan per pengguna.
CREATE TABLE public.leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    year INT NOT NULL,
    total_days INT NOT NULL DEFAULT 12,
    used_days INT NOT NULL DEFAULT 0,
    UNIQUE(user_id, year)
);
-- Tabel untuk notifikasi admin.
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  leave_request_id BIGINT NOT NULL REFERENCES public.leave_requests(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Setup Fungsi Helper Database
-- Fungsi untuk mengambil role pengguna saat ini.
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN (
    SELECT role
    FROM public.profiles
    WHERE id = auth.uid()
  );
END;
$$;
-- Fungsi yang dipanggil oleh trigger untuk menyalin data dari auth.users ke public.profiles saat user baru mendaftar.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER -- Jalankan dengan izin penuh
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, id_pjlp, email, phone)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'name',
    NEW.raw_user_meta_data ->> 'id_pjlp',
    NEW.email,
    NEW.raw_user_meta_data ->> 'phone'
  );
  RETURN NEW;
END;
$$;

-- 3. Setup Row Level Security (RLS)
-- Aktifkan RLS untuk semua tabel.
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Kebijakan untuk 'profiles'
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can view profiles." ON public.profiles;
DROP POLICY IF EXISTS "Admins have full access to profiles." ON public.profiles;
CREATE POLICY "Authenticated users can view profiles." ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins have full access to profiles." ON public.profiles FOR ALL USING ((SELECT get_user_role()) = 'admin');

-- Kebijakan untuk 'leave_requests'
DROP POLICY IF EXISTS "Users can manage their own leave requests." ON public.leave_requests;
DROP POLICY IF EXISTS "Admins can view all leave requests." ON public.leave_requests;
CREATE POLICY "Users can manage their own leave requests." ON public.leave_requests FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all leave requests." ON public.leave_requests FOR SELECT USING ((SELECT get_user_role()) = 'admin');

-- Kebijakan untuk 'leave_balances'
DROP POLICY IF EXISTS "Users can manage their own leave balances." ON public.leave_balances;
DROP POLICY IF EXISTS "Members can view and create their own leave balance." ON public.leave_balances;
DROP POLICY IF EXISTS "Admins can view all leave balances." ON public.leave_balances;
CREATE POLICY "Members can view and create their own leave balance." ON public.leave_balances FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all leave balances." ON public.leave_balances FOR SELECT USING ((SELECT get_user_role()) = 'admin');

-- Kebijakan untuk 'notifications'
DROP POLICY IF EXISTS "Admins can see their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "Admins can update their own notifications" ON public.notifications;
CREATE POLICY "Admins can see their own notifications" ON public.notifications FOR SELECT TO authenticated USING ((SELECT get_user_role()) = 'admin' AND auth.uid() = user_id);
CREATE POLICY "Admins can update their own notifications" ON public.notifications FOR UPDATE TO authenticated USING ((SELECT get_user_role()) = 'admin' AND auth.uid() = user_id);

-- 4. Setup Fungsi untuk Trigger
-- Fungsi untuk membuat notifikasi untuk semua admin saat ada pengajuan baru.
CREATE OR REPLACE FUNCTION public.create_admin_notification_for_new_leave()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  admin_record RECORD;
  applicant_name TEXT;
BEGIN
  SELECT name INTO applicant_name FROM public.profiles WHERE id = NEW.user_id;
  IF applicant_name IS NULL THEN
    applicant_name := 'Seorang anggota';
  END IF;
  FOR admin_record IN SELECT id FROM public.profiles WHERE role = 'admin' LOOP
    INSERT INTO public.notifications (user_id, leave_request_id, message)
    VALUES (admin_record.id, NEW.id, applicant_name || ' mengajukan cuti baru: "' || NEW.title || '"');
  END LOOP;
  RETURN NEW;
END;
$$;
-- Fungsi untuk memperbarui saldo cuti saat status pengajuan berubah.
CREATE OR REPLACE FUNCTION public.handle_leave_balance_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  leave_year INT;
  default_total_days INT := 12;
BEGIN
  leave_year := EXTRACT(YEAR FROM NEW.start_date);
  
  -- Pastikan data saldo cuti ada, jika tidak buat baru. Ini KUNCI perbaikan.
  INSERT INTO public.leave_balances (user_id, year, total_days, used_days)
  VALUES (NEW.user_id, leave_year, default_total_days, 0)
  ON CONFLICT (user_id, year) DO NOTHING;

  -- Jika status diubah menjadi 'Disetujui' dari status lain.
  IF NEW.status = 'Disetujui' AND OLD.status != 'Disetujui' THEN
    UPDATE public.leave_balances
    SET used_days = used_days + NEW.duration
    WHERE user_id = NEW.user_id AND year = leave_year;

  -- Jika persetujuan dibatalkan (dari 'Disetujui' menjadi status lain).
  ELSIF OLD.status = 'Disetujui' AND NEW.status != 'Disetujui' THEN
    UPDATE public.leave_balances
    SET used_days = used_days - NEW.duration
    WHERE user_id = NEW.user_id AND year = leave_year;
  END IF;

  RETURN NEW;
END;
$$;

-- 5. Setup Trigger Database
-- Trigger untuk `handle_new_user` saat ada user baru.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
-- Trigger untuk membuat notifikasi admin saat ada pengajuan baru.
CREATE TRIGGER on_new_leave_request_insert
  AFTER INSERT ON public.leave_requests
  FOR EACH ROW EXECUTE PROCEDURE public.create_admin_notification_for_new_leave();
-- Trigger untuk memperbarui saldo cuti saat status diubah.
CREATE TRIGGER on_leave_request_status_change
  AFTER UPDATE ON public.leave_requests
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE PROCEDURE public.handle_leave_balance_update();

-- Selesai: Skema database SIAP CUTI telah lengkap dan siap digunakan.
